import os

DEBUG = True
APP_SECRET_KEY = os.environ["APP_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = "sqlite:///db/dati.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
JWT_BLOCKLIST_ENABLED = True
JWT_BLOCKLIST_TOKEN_CHECKS = ["access", "refresh"]
JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
