"""Aggiunge la relazione tra negozi ed utenti

Revision ID: 0c78bef9807b
Revises: 
Create Date: 2021-11-24 07:57:22.971414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c78bef9807b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("negozi", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "negozi_utenti_id_utente_fkey", "utenti", ["titolare_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("negozi", schema=None) as batch_op:
        batch_op.drop_constraint("negozi_utenti_id_utente_fkey", type_="foreignkey")

    # ### end Alembic commands ###
