"""modifica la tabella ordini_oggetti con la quantita

Revision ID: 77856d326dcb
Revises: cabea13cf293
Create Date: 2021-12-01 18:29:06.726057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77856d326dcb"
down_revision = "cabea13cf293"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ordini_oggetti", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("quantita", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ordini_oggetti", schema=None) as batch_op:
        batch_op.drop_column("quantita")
        batch_op.drop_column("id")

    # ### end Alembic commands ###
