"""aggiunta la data di creazione dell'ordine

Revision ID: 835a16f09d64
Revises: 77856d326dcb
Create Date: 2021-12-05 12:56:46.323122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835a16f09d64'
down_revision = '77856d326dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordini', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_creazione', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordini', schema=None) as batch_op:
        batch_op.drop_column('data_creazione')

    # ### end Alembic commands ###
